name: "jaguarportal-submit"
description: "Submit result analysis SBFL to Jaguar Portal"
author: "ericksonlbs"

inputs:
  jaguarPortalProjectKey:
    description: "The key of the Jaguar Portal project"
    required: true
  jaguarPortalProjectName:
    description: "The name of the Jaguar Portal project"
    required: true
  jaguarPortalHostUrl:
    description: "The Jaguar Portal server URL"
    default: https://jaguarportalcloud.io
    required: true
  jaguarPortalAPIKey:
    description: "The APIKey from Jaguar Portal"
    required: true
  jaguarPortalAnalisysPath:
    description: "The analisys path"
    required: true
    default: /target/.jaguar    
  jaguarPortalClassesPath:
    description: "The classes path"
    required: true
    default: /target/src/main/java
    
    ANALISYS
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: 'check-square'
  color: 'blue'
